all:
	./setup.sh

update-user-js:
	curl 'https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js' >user.ghacks.js
	curl 'https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js' >user.pyllyukko.js
