# Colors from the current theme, see ~/.dotfiles/themes/
[general]
import = ["~/.config/theme/alacritty.toml"]

[window]
dimensions = { columns = 120, lines = 40 }
padding = { x = 2, y = 2 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "Iosevka", style = "Medium" }
bold = { family = "Iosevka", style = "Bold" }
italic = { family = "Iosevka", style = "Medium Italic" }
size = 12.0

[mouse]
hide_when_typing = true

# Autostart tmux as alacritty doesn't have native tabs
[terminal.shell]
program = "tmux"
args = ["new-session", "-A", "-s", "alacritty"]

# Ctrl+Shift+T for tmux as explicit CSI u sequence
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u001B[116;6u"
