#!/bin/bash
set -e -u -o pipefail

repository_cache="/var/tmp"
if [[ -d "/var/ext/$UID" ]]; then
  repository_cache="/var/ext/$UID"
  if [[ -d ~/.cache && ! -L ~/.cache/bazel && ! -d ~/.cache/bazel ]]; then
    ln -s /var/ext/$UID ~/.cache/bazel
  fi
fi

echo "# Autogenerated by ~/.dotfiles/bazelrc.sh"
echo "build --repository_cache=$repository_cache"
