# Generates ~/.gitconfig
set -e -u -o pipefail
mkdir -p -m 0555 ~/.dotfiles/.empty
cat <<EOF
# Autogenerated by ~/.dotfiles/gitconfig.sh

[include]
	path = ~/.dotfiles/gitconfig.base

[init]
	# Point to an empty directory to avoid copying sample hooks to every repo
	# Look for sample hooks in /usr/share/git-core/templates/hooks/
	templateDir = ~/.dotfiles/.empty/

[user]
	name = Ivan Krasilnikov
	email = $(echo -e "\\x69\\x76\\x61\\x6e\\x6b\\x40\\x69\\x76\\x61\\x6e\\x6b\\x2e\\x6d\\x65")
EOF
