# Generates ~/.gitconfig
set -e -u -o pipefail
mkdir -p -m 0555 ~/.dotfiles/.empty
cat <<EOF
# Autogenerated by ~/.dotfiles/gitconfig.sh

[include]
	path = ~/.dotfiles/gitconfig.base

[init]
	# Point to an empty directory to avoid copying sample hooks to every repo
	# Look for sample hooks in /usr/share/git-core/templates/hooks/
	templateDir = ~/.dotfiles/.empty/

[user]
	name = Ivan Krasilnikov
	email = $(echo -e "\\x69\\x76\\x61\\x6e\\x6b\\x40\\x69\\x76\\x61\\x6e\\x6b\\x2e\\x6d\\x65")
EOF

if command -v git-lfs >/dev/null; then
  cat <<'EOF'

[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
EOF
fi

# sudo apt install git-delta
if command -v delta >/dev/null; then
  cat <<'EOF'

[core]
	pager = delta

[include]
	path = ~/.dotfiles/gitconfig.delta

[interactive]
	diffFilter = delta --color-only

[diff]
	# Git's whitespace-error colouring leaves the indent of moved (colorMoved) lines
	# uncoloured, so delta's map-styles can't restyle it; delta flags whitespace itself
	wsErrorHighlight = none
EOF
fi
