#!/bin/bash
source ~/.dotfiles/setup.lib.sh

cat <<EOF
# Autogenerated by ~/.dotfiles/gitconfig.sh

[user]
name = ${SCM_NAME}
email = ${SCM_EMAIL}

[color]
ui = auto

[alias]
amend = commit --amend
br = branch
ci = commit
cia = commit --amend
co = checkout
cp = cherry-pick
detach = !git checkout HEAD^0
g = !gitg
lg = log --pretty=oneline --abbrev-commit --decorate
root = rev-parse --show-toplevel
st = status
unstage = reset HEAD --

# git gc with pruning. add --aggressive for more effect.
gca = !git -c gc.reflogExpire=0 -c gc.reflogExpireUnreachable=0 \
        -c gc.rerereresolved=0 -c gc.rerereunresolved=0 \
        -c gc.pruneExpire=now gc --prune=now

[push]
default = matching

[core]
pager = less -FSRXi

[init]
# Point to empty directory to avoid create sample hooks
templateDir = /usr/share/git-core/templates/branches/

[url "git@github.com:github"]
insteadOf = "git://github.com/github"
insteadOf = "github:github"
insteadOf = "https://github.com/github"

[url "git@github.com:"]
pushInsteadOf = "git://github.com/"
pushInsteadOf = "github:"
pushInsteadOf = "https://github.com/"

[url "git://github.com/"]
insteadOf = "github:"

[url "git@gist.github.com:"]
insteadOf = "gst:"
pushInsteadOf = "gist:"
pushInsteadOf = "git://gist.github.com/"

[url "git://gist.github.com/"]
insteadOf = "gist:"
EOF

if [[ -f ~/.private/gitconfig ]]; then
  echo
  echo "[include]"
  echo "path = ~/.private/gitconfig"
fi
