# Generates ~/.hgrc
set -e -u -o pipefail

cd "$(dirname "$(readlink -f "$0")")"

SCM_NAME=$(bash ./gitconfig.sh | sed -ne 's/^\s*name = //p')
SCM_EMAIL=$(bash ./gitconfig.sh | sed -ne 's/^\s*email = //p')

cat <<EOF
# Autogenerated by ~/.dotfiles/hgrc.sh

[ui]
username = ${SCM_NAME} <${SCM_EMAIL}>
EOF
