#!/usr/bin/env bash
# Installs/reinstall dotfiles. Can be rerun multiple times.
set -e
source "${BASH_SOURCE[0]%/*}/setup.lib.sh"

if ! [[ -f "$HOME/.dotfiles/setup" && "$HOME/.dotfiles/setup" -ef "$0" ]]; then
  echo "Error: dotfiles must be installed in ~/.dotfiles"
  exit 1
fi
cd ~/.dotfiles

rm_dotfiles_symlinks ~/.config/mpv ~/.config/mpv/input.conf ~/.config/qpdfview ~/.config/qpdfview/shortcuts.conf

gen -c <(./gitconfig.sh) ~/.gitconfig
gen -c <(./hgrc.sh) ~/.hgrc

link Rprofile
link bash_logout
link bashrc
link fonts
link gdb
link gdbinit
link htoprc ~/.config/htop/htoprc
link hushlogin
link inputrc
link ipython_config.py ~/.ipython/profile_default/ipython_config.py
link jupyter
link profile
link tmux.conf
link vim
link vimrc

if [[ $UID != 0 ]]; then
  copy mpv/input.conf ~/.config/mpv/input.conf
  gen <(./mpv/mpv.conf.sh) ~/.config/mpv/mpv.conf
  copy qpdfview-shortcuts.conf ~/.config/qpdfview/shortcuts.conf
  copy vlcrc ~/.config/vlc/vlcrc
  link tkdiffrc
  link xinitrc
  link xonshrc
  link xsessionrc
fi

if ! [[ -d ~/.local/bin ]]; then
  mkdir -p ~/.local/bin
  echo "Created: ~/.local/bin"
fi

if ! [[ -d ~/.bin ]]; then
  ln -s .local/bin ~/.bin
  echo "Linked: ~/.bin -> ~/.local/bin"
fi

# ~/.ssh {{{
mkdir -p ~/.ssh
chmod 0700 ~/.ssh

if [[ -L ~/.ssh/config && ~/.ssh/config -ef ~/.dotfiles/ssh_config ]]; then
  rm -rf ~/.ssh/config ~/.ssh/control ~/.dotfiles/{ssh_config,gitconfig,hgrc}
fi

gen -c <(./ssh-config.sh) ~/.ssh/config

chmod 0600 ~/.ssh/config
if [[ -f ~/.ssh/authorized_keys ]]; then
  chmod 0600 ~/.ssh/authorized_keys
fi
# }}}

if [[ -d ~/.gnupg/ ]]; then
  chmod og-rwx ~/.gnupg/
fi

# Fix gnome-keyring pre 3.28 for ed25519 keys {{{
if [[ -f ~/.ssh/id_ed25519 &&
      -x /usr/bin/gnome-keyring-daemon &&
      -x /usr/bin/gnome-keyring &&
      "$(/usr/bin/gnome-keyring version | egrep -o '[0-9.]+')" < 3.28 ]]; then
  if ! [[ assets/keychain-ssh.desktop -ef ~/.config/autostart/gnome-keyring-ssh.desktop ]]; then
    mkdir -p ~/.config/autostart
    ln -sf ../../.dotfiles/assets/keychain-ssh.desktop ~/.config/autostart/gnome-keyring-ssh.desktop
    echo "Fixed up gnome-keyring-ssh"
  fi

  if ! [[ -x /usr/bin/keychain ]]; then
    echo -e "Action required: sudo apt-get install keychain"
  fi

  if [[ -f /etc/xdg/autostart/gnome-keyring-ssh.desktop ]]; then
    echo -e "Action required: sudo rm -f /etc/xdg/autostart/gnome-keyring-ssh.desktop"
  fi
fi
# }}}

if [[ -x /usr/bin/byobu && ! -f ~/.byobu/.welcome-displayed ]]; then
  mkdir -p ~/.byobu
  touch ~/.byobu/.welcome-displayed
  echo "Touched ~/.byobu/.welcome-displayed"
fi

gen <(./jupyter/jupyter_notebook_config.json.sh) jupyter/jupyter_notebook_config.json

if [[ -f ~/.dotfiles/setup.local ]]; then
  echo "Running ~/.dotfiles/setup.local"
  source ~/.dotfiles/setup.local
fi

rm -rf python/dotfiles/__pycache__
