#!/bin/bash
# Installs/reinstall dotfiles. Can be rerun multiple times.
set -e -u -o pipefail
umask 077

if ! [[ -f "$HOME/.dotfiles/setup.sh" ]]; then
  echo "Error: dotfiles must be installed in ~/.dotfiles"
  exit 1
fi

# Common setup vars
if [[ -f ~/.dotfiles/setup.vars ]]; then
  source ~/.dotfiles/setup.vars
fi
if [[ -f ~/.local/dotfiles/setup.vars ]]; then
  source ~/.local/dotfiles/setup.vars
fi

# Helper functions {{{

# setup_gen [--backup] [-c|--check] <generated source file> <destination path>
#   --backup: back up destination file with .bak suffix
#   --check: check for "# Autogenerated" marker, do not overwrite if missing
setup_gen() {
  local check=0
  local backup=0
  while [[ $# > 2 ]]; do
    case "$1" in
      -c|--check) check=1;;
      --backup) backup=1;;
    esac
    shift
  done

  local dst="$2"
  local tmp="$(mktemp)"
  cat "$1" >"$tmp"

  if ((check)) && [[ -s "$dst" ]] &&
     ! grep -q '^# Autogenerated' "$dst"; then
    echo "Ignoring $dst - local version"
    rm -f "$tmp"
    return
  fi

  if [[ -s "$dst" ]] && grep -q "^# Local changes" "$dst"; then
    grep -A 10000 "^# Local changes" "$dst" >>"$tmp"
  fi

  if [[ -L "$dst" ]]; then
    rm -f "$dst"
  fi

  if ! cmp --silent "$dst" "$tmp"; then
    echo "Generated $dst"
    local dstdir=$(dirname -- "$dst")
    if ! [[ -d "$dstdir" ]]; then
      mkdir -p "$dstdir"
    fi
    if ((backup)) && [[ -f "$dst" ]]; then
      echo "Backed up $dst to $dst.bak"
      mv -f "$dst" "$dst.bak"
    fi
    mv -f "$tmp" "$dst"
  else
    rm -f "$tmp"
  fi
}

ln_sr() {
  if [[ "$OSTYPE" == darwin* ]]; then
    if hash gln >/dev/null 2>&1; then
      gln -s -r "$@"
    else
      ln -s "$@"
    fi
  else
    ln -s -r "$@"
  fi
}

link_or_copy() {
  local op="$1"; shift
  if [[ "$OSTYPE" == darwin* ]]; then
    local src_path=$HOME/.dotfiles/"$1"
  else
    local src_path=$(cd ~/.dotfiles; readlink -f "$1")
  fi
  local dst_path="${2:-$HOME/.$(basename "$1")}"

  local dst_dir="$(dirname "$dst_path")"
  if ! [[ -d "$dst_dir" ]]; then
    mkdir -p -m 0700 "$dst_dir"
    echo "Created $dst_dir"
  fi

  if ! [[ -e "$src_path" ]]; then
    echo "Error: $src_path doesn't exist"
    exit 1
  fi

  if [[ "$op" == "copy" ]]; then
    if realpath -- "$dst_dir" | grep -q dotfiles; then
      echo "Error: $dst_dir is symlinking inside ~/.dotfiles/"
      exit 1
    fi

    if [[ -L "$dst_path" ]]; then
      rm -f "$dst_path"
      cp -a "$src_path" "$dst_path"
      echo "Copied $src_path over symlink $dst_path"
    elif ! [[ -f "$dst_path" ]]; then
      cp -af "$src_path" "$dst_path"
      echo "Copied $src_path to $dst_path"
    elif ! cmp --silent "$src_path" "$dst_path"; then
      cp -af "$src_path" "$dst_path"
      echo "Copied $src_path over existing file $dst_path"
    fi
    return
  fi

  if [[ "$op" == "link" ]]; then
    if [[ -e "$dst_path" ]]; then
      if [[ "$src_path" -ef "$dst_path" ]]; then
        return 0
      elif [[ -d "$dst_path" ]]; then
        rm -rf "$dst_path"
        ln_sr "$src_path" "$dst_path"
        echo "Replaced directory: $dst_path -> $src_path";
      else
        rm -f "$dst_path"
        ln_sr "$src_path" "$dst_path"
        echo "Replaced: $dst_path -> $src_path"
      fi
    elif [[ -L "$dst_path" ]]; then
      rm -f "$dst_path"
      ln_sr "$src_path" "$dst_path"
      echo "Fixed broken link: $dst_path -> $src_path"
    else
      ln_sr "$src_path" "$dst_path"
      echo "Linked: $dst_path -> $src_path"
    fi
    return
  fi
}

setup_ln() { link_or_copy link "$@"; }
setup_cp() { link_or_copy copy "$@"; }

# setup_cp_dir <source dir> <destination dir>
# Recursively copies a directory, overwriting existing files.
# A destination symlink left over from an older setup_ln is replaced with a dir.
setup_cp_dir() {
  if [[ "$OSTYPE" == darwin* ]]; then
    local src_path=$HOME/.dotfiles/"$1"
  else
    local src_path=$(cd ~/.dotfiles; readlink -f "$1")
  fi
  local dst_path="${2%/}"
  local dst_dir="$(dirname "$dst_path")"
  local dotfiles_dir="$(cd ~/.dotfiles; pwd -P)"
  local src dst dst_real

  if ! [[ -d "$src_path" ]]; then
    echo "Error: $src_path doesn't exist"
    exit 1
  fi

  if [[ -L "$dst_path" ]]; then
    rm -f "$dst_path"
    echo "Removed symlink $dst_path"
  fi
  if [[ -d "$dst_dir" ]]; then
    dst_real="$(cd "$dst_dir"; pwd -P)"
    if [[ "$dst_real" == "$dotfiles_dir" || "$dst_real" == "$dotfiles_dir"/* ]]; then
      echo "Error: $dst_dir is symlinking inside ~/.dotfiles/"
      exit 1
    fi
  fi
  if ! [[ -d "$dst_path" ]]; then
    rm -f "$dst_path"
    mkdir -p -m 0700 "$dst_path"
    echo "Created $dst_path"
  fi

  # find lists a directory before its contents, so parents exist in time
  while IFS= read -r -d '' src; do
    dst="$dst_path/${src#$src_path/}"
    if [[ -d "$src" ]]; then
      if ! [[ -d "$dst" ]]; then
        rm -f "$dst"
        mkdir -p -m 0700 "$dst"
        echo "Created $dst"
      fi
    elif [[ -L "$dst" || ! -f "$dst" ]] || ! cmp --silent "$src" "$dst"; then
      rm -rf "$dst"
      cp -af "$src" "$dst"
      echo "Copied $src to $dst"
    fi
  done < <(find "$src_path" -mindepth 1 -name .gitignore -prune -o -print0)
}

remove_dotfiles_symlinks() {
  for f in "$@"; do
    if [[ -L "$f" ]] && (readlink -f -- "$f" | fgrep -q /.dotfiles/); then
      rm -rf "$f"
      echo "Removed obsolete symlink $f"
    fi
  done
}

# }}}

if ! [[ -f "$HOME/.dotfiles/setup.sh" && "$HOME/.dotfiles/setup.sh" -ef "$0" ]]; then
  if [[ $UID == 0 ]]; then
    SCRIPT_PATH=$(readlink -f "$0")
    SCRIPT_USER=$(stat -c %U "$SCRIPT_PATH")
    if [[ "$SCRIPT_PATH" == "/home/$SCRIPT_USER/"* ]]; then
      echo "Will run setup under $SCRIPT_USER"
      (set -x; sudo -u "$SCRIPT_USER" "$SCRIPT_PATH")
      exit $?
    fi
  fi
  echo "Error: dotfiles must be installed in ~/.dotfiles"
  exit 1
fi
cd ~/.dotfiles

if [[ -z "${USER:-}" ]]; then
  USER=$(whoami)
  if [[ -z "${USER:-}" ]]; then
    USER=$(id -u -n)
  fi
fi

IN_CONTAINER=0
if [[ "${container:-}" != "" || -f /run/.containerenv || -f /.dockerenv ]]; then
  IN_CONTAINER=1
fi

# When running under root, verify that home directory is /root to avoid
# accidentally messing up another user's home directory.
#
# Skip for containers to support rootless containers with container root
# mapped to current user on the host with HOME passed through.
if [[ $UID == 0 && $IN_CONTAINER == 0 ]]; then
  ROOT_HOME="$(cat /etc/passwd | grep ^root: | cut -f 6 -d :)"
  if ! [[ $HOME -ef $ROOT_HOME ]]; then
    echo "Error: HOME=$HOME doesn't match root's home from /etc/passwd: $ROOT_HOME"
    exit 1
  fi
fi

remove_dotfiles_symlinks \
  ~/.config/autostart/gnome-keyring-ssh.desktop \
  ~/.config/qpdfview \
  ~/.config/qpdfview/shortcuts.conf \
  ~/.fonts \
  ~/.gdb \
  ~/.local/bin/code \
  ~/.sqliterc

if [[ -L ~/.bin && "$(readlink ~/.bin)" == ".local/bin" ]]; then
  (set -x; rm -f ~/.bin)
fi

# Keep a remote pointing at the upstream repo, even if origin is a local mirror.
# -m sets refs/remotes/github/HEAD, i.e. the remote's default branch.
if [[ -f ~/.dotfiles/.git/config ]] && hash git >/dev/null 2>&1 &&
   ! grep -q '^\[remote "github"\]' ~/.dotfiles/.git/config; then
  (set -x; git remote add -m master github https://github.com/ivankra/dotfiles.git)
fi

if [[ -f ~/.dotfiles/gitconfig.local ]]; then
  setup_ln gitconfig.local ~/.gitconfig
else
  setup_gen -c <(bash ./gitconfig.sh) ~/.gitconfig
fi
setup_gen -c <(bash ./hgrc.sh) ~/.hgrc

setup_ln bash_logout
setup_ln bashrc
setup_ln gdbinit
setup_ln hushlogin
setup_ln inputrc
setup_ln profile
setup_ln vim
setup_ln vimrc

setup_ln alacritty.toml ~/.config/alacritty/alacritty.toml
setup_ln htoprc ~/.config/htop/htoprc
setup_ln kitty.conf ~/.config/kitty/kitty.conf
setup_ln nvim ~/.config/nvim
setup_ln nvim/site ~/.local/share/nvim/site
setup_ln wezterm.lua ~/.config/wezterm/wezterm.lua

if hash tmux >/dev/null 2>&1; then
  setup_ln tmux.conf
fi
if hash ipython >/dev/null 2>&1 || hash ipython3 >/dev/null 2>&1; then
  #setup_gen <(./jupyter/jupyter_notebook_config.json.sh) ~/.dotfiles/jupyter/jupyter_notebook_config.json
  setup_ln ipython_config.py ~/.ipython/profile_default/ipython_config.py
fi
if hash jupyter >/dev/null 2>&1 || hash jupyter-notebook >/dev/null 2>&1; then
  setup_ln jupyter
fi
if hash R >/dev/null 2>&1; then
  setup_ln Rprofile
fi

if [[ $UID != 0 ]]; then
  setup_cp mpv/input.conf ~/.config/mpv/input.conf
  setup_ln mpv/scripts ~/.config/mpv/scripts
  setup_gen <(./mpv/mpv.conf.sh) ~/.config/mpv/mpv.conf
  setup_cp vlcrc ~/.config/vlc/vlcrc

  if hash tkdiff >/dev/null 2>&1; then
    setup_ln tkdiffrc
  fi

  if hash xonsh >/dev/null 2>&1; then
    setup_ln xonshrc
  fi

  if hash keepassxc >/dev/null 2>&1; then
    mkdir -p ~/.local/share/applications
    setup_cp keepassxc.desktop ~/.local/share/applications/org.keepassxc.KeePassXC.desktop
    setup_ln keepassxc.ini ~/.config/keepassxc/keepassxc.ini
  else
    rm -f ~/.local/share/applications/org.keepassxc.KeePassXC.desktop
  fi

  if hash virt-manager >/dev/null 2>&1; then
    mkdir -p ~/.local/share/applications
    setup_cp virt-manager.desktop ~/.local/share/applications/virt-manager.desktop
  else
    rm -f ~/.local/share/applications/virt-manager.desktop
  fi

  if [[ "$OSTYPE" != darwin* ]]; then
    setup_cp_dir fcitx5 ~/.config/fcitx5
    setup_cp okularpartrc ~/.config/okularpartrc
    setup_ln plasma-localerc ~/.config/plasma-localerc
    setup_cp qpdfview-shortcuts.conf ~/.config/qpdfview/shortcuts.conf
    setup_gen --backup <(bash ./qpdfview.sh) ~/.config/qpdfview/qpdfview.conf
    setup_gen <(bash ./qt5ct.sh) ~/.config/qt5ct/qt5ct.conf
    setup_ln xinitrc
    setup_ln xsessionrc
    rm -f ~/.local/share/applications/gnome-system-monitor.desktop
  fi
fi

if [[ "$OSTYPE" != darwin* ]]; then
  ./mimeapps.py
fi

mkdir -p -m 0700 ~/.ssh
setup_gen -c <(bash ./ssh-config.sh) ~/.ssh/config
chmod 0700 ~/.ssh
chmod 0600 ~/.ssh/config
if [[ -f ~/.ssh/authorized_keys ]]; then
  chmod 0600 ~/.ssh/authorized_keys
fi

# don't show welcome message and mess up with prompt on first run
if hash byobu >/dev/null 2>&1; then
  for f in ~/.byobu/{prompt,.welcome-displayed}; do
    if ! [[ -f "$f" ]]; then
      mkdir -m 0700 -p ~/.byobu
      (set -x; touch "$f")
    fi
  done
fi

if ! [[ -d ~/.local/bin ]]; then
  (set -x; mkdir -p ~/.local/bin)
fi

if [[ -d ~/.gnupg/ ]]; then
  chmod og-rwx ~/.gnupg
fi

if ! [[ -e ~/.history ]]; then
  mkdir -p -m 0700 ~/.history
fi
if [[ -d ~/.history ]]; then
  chmod 0700 ~/.history
fi

if [[ -f ~/.bash_history && ! -L ~/.bash_history ]]; then
  echo "Warning: orphan ~/.bash_history file"
  chmod og-rwx ~/.bash_history
fi

setup_xfs_symlinks() {
  local xfsroot="/xfs"
  local xfshome="/xfs/$USER"
  local it

  if [[ "$OSTYPE" == darwin* ]]; then
    return 0
  fi

  if ! [[ -d "$xfshome" ]]; then
    if [[ $UID != 0 && -d "$xfsroot" ]] && mountpoint "$xfsroot" >/dev/null 2>&1; then
      mkdir -m 0750 "$xfshome" >/dev/null 2>&1 || true
    fi
    if ! [[ -d "$xfshome" ]]; then
      # Remove possible dead symlinks, unless it seems like xfs isn't mounted
      for it in ~/.local/share/{containers,flatpak} ~/.cache; do
        if [[ -L "$it" && ! -d "$it" ]]; then
          if [[ "$(readlink "$it")" == $xfsroot/* ]] && fgrep " $xfsroot " /etc/fstab >/dev/null 2>&1; then
            continue
          fi
          rm -f "$it"
        fi
      done
      return 0
    fi
  fi

  if [[ $UID == 0 || $USER == nobody || ! -d "/home/$USER" ]]; then
    return 0
  fi

  if ! [[ -d ~/.local/share ]]; then
    mkdir -p -m 0700 ~/.local ~/.local/share
  fi

  for it in \
      "$xfshome/cache=$HOME/.cache" \
      "$xfshome/containers=$HOME/.local/share/containers" \
      "$xfshome/flatpak=$HOME/.local/share/flatpak"; do
    local src="${it#*=}"
    local target="${it%=*}"
    if ! [[ -d "$target" ]]; then
      mkdir -m 0750 "$target" || true
      if ! [[ -d "$target" ]]; then
        continue
      fi
    fi
    if [[ -d "$src" ]]; then
      continue
    fi
    if [[ -L "$src" ]]; then
      rm -f "$src" || true
    fi
    ln -sf "$target" "$src"
    echo "Symlinked $src -> $target"
  done
}
setup_xfs_symlinks

rm -rf python/dotfiles/__pycache__

if [[ -x ~/.local/dotfiles/setup.sh ]]; then
  (set -x; ~/.local/dotfiles/setup.sh)
fi
