#!/usr/bin/env bash
# Installes/reinstall dotfiles. Can be rerun multiple times.

install_link() {
  local src=".dotfiles/$1"
  local dst=".$(basename "$1")"

  local src_path="$HOME/$src"
  local dst_path="$HOME/$dst"

  if ! [[ -e "$src_path" ]]; then
    echo "Error: $src_path doesn't exist"
    exit 1
  fi

  if [[ -e "$dst_path" ]]; then
    if [[ "$src_path" -ef "$dst_path" ]]; then
      return 0
    elif [[ -d "$dst_path" ]]; then
      rm -rf "$dst_path"
      ln -s "$src" "$dst_path"
      echo "Replaced directory: ~/$dst -> $src";
    else
      rm -f "$dst_path"
      ln -s "$src" "$dst_path"
      echo "Replaced: ~/$dst -> $src"
    fi
  elif [[ -L "$dst_path" ]]; then
    rm -f "$dst_path"
    ln -s "$src" "$dst_path"
    echo "Fixed broken link: ~/$dst -> $src"
  else
    ln -s "$src" "$dst_path"
    echo "Linked: ~/$dst -> $src"
  fi
}

if ! [[ -f "$HOME/.dotfiles/setup" && "$HOME/.dotfiles/setup" -ef "$0" ]]; then
  echo "Error: dotfiles must be installed in ~/.dotfiles"
  exit 1
fi

cd "$HOME/.dotfiles"
bash ./setup-gen

FILES=(
  Rprofile
  bash_logout
  bashrc
  fonts
  hgrc
  gdb
  gdbinit
  gitconfig
  inputrc
  profile
  tkdiffrc
  tmux.conf
  vim
  vimrc
  xinitrc
)
for f in "${FILES[@]}"; do
  install_link "$f"
done

if [[ -x /usr/bin/gnome-keyring-daemon &&
      -x /usr/bin/keychain &&
      -f ~/.ssh/id_ed25519 &&
      fix/keychain-ssh.desktop -ef ~/.config/autostart/gnome-keyring-ssh.desktop ]]; then
  mkdir -p ~/.config/autostart
  ln -sf ~/.dotfiles/fix/keychain-ssh.desktop ~/.config/autostart/gnome-keyring-ssh.desktop
  #ln -sf ~/.dotfiles/fix/keychain-gpg.desktop ~/.config/autostart/gnome-keyring-gpg.desktop
  echo "Fixed up gnome keyring"

  if [[ -f /etc/xdg/autostart/gnome-keyring-ssh.desktop ]]; then
    echo "Action required to complete keyring fix:"
    echo "  1) sudo rm -f /etc/xdg/autostart/gnome-keyring-ssh.desktop"
    echo "  2) add 'Host *', 'AddKeysToAgent yes' to ~/.ssh/config"
  fi
fi
