#!/bin/bash

echo '# Autogenerated by ~/.dotfiles/ssh-config-gen.sh
AddKeysToAgent yes
Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Compression no
HashKnownHosts no
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
ServerAliveInterval 30
ServerAliveCountMax 6
TCPKeepAlive no'

if [[ $UID != 0 ]]; then
  echo 'ControlMaster auto'
  echo 'ControlPath ~/.ssh/socket/%r@%h:%p'
  echo 'ControlPersist 300'
  mkdir -p ~/.ssh/socket
  chmod 0700 ~/.ssh ~/.ssh/socket
fi

if [[ -f ~/.ssh/id_ed25519 ]]; then
  echo "IdentityFile ~/.ssh/id_ed25519"
fi

if [[ -f ~/.ssh/id_rsa ]]; then
  echo "IdentityFile ~/.ssh/id_rsa"
fi

echo

for f in $(ls -A ~/.ssh | LC_ALL=C sort -V); do
  if [[ -d ~/.ssh/"$f" && -f ~/.ssh/"$f"/config ]]; then
    echo "Include ~/.ssh/$f/config"
  elif [[ "$f" == config.* ]]; then
    echo "Include ~/.ssh/$f"
  fi
done
