#!/usr/bin/env python3

XONSH_COLOR_STYLE='fruity'

try:
  import pandas as pd
  import numpy as np
  import matplotlib as mpl
  import matplotlib.pyplot as plt
  import sys, os, re
except:
  pass

def _import_bashrc_aliases():
  global aliases
  for line in open(os.environ['HOME'] + '/.bashrc'):
    m = re.match('^alias (\w+)=(.+)$', line)
    if m:
      key = m.group(1)
      val = m.group(2)
      if val[0] in "\"'": val = val[1:-1]
      if '$' in val or '|' in val: continue
      aliases[key] = val

_import_bashrc_aliases()
