# Shared rules for the agent sandbox images built on top of agents-base.
#
# A per-agent Makefile is just:
#
#     ARGS := -c check_for_update_on_startup=false   # optional, passed to CMD
#     LAUNCHERS := foo foo2   # optional, defaults to the image name
#     include ../agents-base/build.mk
#
# `make build` builds the image and installs a launcher script into $(BINDIR),
# so the containerised CLI sits on $PATH instead of needing a shell alias.
# The script is written under the first name in LAUNCHERS and the rest are
# symlinks to it. Like dvim's run.sh, it dispatches on basename $0: each name
# runs the same image with its own /root, ~/.docker/<name>.
#
# Paths are resolved relative to this file, so this directory can be copied
# anywhere and still build: nothing outside it is referenced.

BUILD_MK := $(abspath $(lastword $(MAKEFILE_LIST)))
DR       := $(abspath $(dir $(BUILD_MK))../dr)

IMAGE  := $(notdir $(CURDIR))
CMD    ?= $(IMAGE)
ARGS   ?=
BINDIR ?= $(HOME)/.local/bin

LAUNCHERS ?= $(IMAGE)
LAUNCHER  := $(BINDIR)/$(firstword $(LAUNCHERS))
MARKER    := dotfiles-docker-launcher

space := $(subst ,, )

# Warn if the launcher will not be reachable.
define warn-unless-on-path
	case ":$$PATH:" in \
	  *":$(BINDIR):"*) ;; \
	  *) echo "warning: $(BINDIR) is not on your PATH; add it with" >&2; \
	     echo "  echo 'export PATH=\"$(BINDIR):\$$PATH\"' >>~/.bashrc" >&2 ;; \
	esac
endef

.PHONY: all deps build image image-nocache rebuild launcher

all: deps build

deps:
	$(MAKE) -C ../agents-base

build: image launcher

rebuild: image-nocache launcher

image:
	podman build -t $(IMAGE) .

image-nocache:
	podman build -t $(IMAGE) --no-cache .

# Refuse to clobber a real binary: several of these CLIs install themselves to
# ~/.local/bin under the same name. Only our own script, or a symlink to it,
# gets replaced.
launcher:
	@mkdir -p $(BINDIR)
	@for name in $(LAUNCHERS); do \
		l=$(BINDIR)/$$name; \
		if [ -L $$l ]; then \
			[ "$$(readlink $$l)" = "$(LAUNCHER)" ] && continue; \
		elif [ ! -e $$l ] || grep -qF $(MARKER) $$l; then \
			continue; \
		fi; \
		echo "$$l exists and was not generated here; refusing to overwrite" >&2; \
		exit 1; \
	done
	@rm -f $(LAUNCHER)
	@printf '%s\n' \
		'#!/bin/sh' \
		'# $(MARKER): generated by $(CURDIR)/Makefile, edits will be lost' \
		'name=$$(basename "$$0")' \
		'case "$$name" in' \
		'  $(subst $(space),|,$(strip $(LAUNCHERS)))) ;;' \
		'  *) echo "$$0: expected to be invoked as one of: $(strip $(LAUNCHERS))" >&2; exit 1 ;;' \
		'esac' \
		'$(strip exec $(DR) -v "$$HOME/.docker/$$name:/root" $(IMAGE) $(CMD) $(ARGS)) "$$@"' \
		> $(LAUNCHER)
	@chmod +x $(LAUNCHER)
	@echo "installed $(LAUNCHER)"
	@for name in $(wordlist 2,$(words $(LAUNCHERS)),$(LAUNCHERS)); do \
		ln -sfn $(LAUNCHER) $(BINDIR)/$$name && echo "linked $(BINDIR)/$$name -> $(LAUNCHER)"; \
	done
	@$(warn-unless-on-path)
