# Shared rules for the agent sandbox images built on top of agents-base.
#
# A per-agent Makefile is just:
#
#     ARGS := -c check_for_update_on_startup=false   # optional, passed to CMD
#     include ../agents-base/build.mk
#
# `make build` builds the image and installs a launcher script into $(BINDIR),
# so the containerised CLI sits on $PATH instead of needing a shell alias.
#
# Paths are resolved relative to this file, so this directory can be copied
# anywhere and still build: nothing outside it is referenced.

BUILD_MK := $(abspath $(lastword $(MAKEFILE_LIST)))
DR       := $(abspath $(dir $(BUILD_MK))../dr)

IMAGE  := $(notdir $(CURDIR))
CMD    ?= $(IMAGE)
ARGS   ?=
BINDIR ?= $(HOME)/.local/bin

LAUNCHER := $(BINDIR)/$(IMAGE)
MARKER   := dotfiles-docker-launcher

# Warn if the launcher will not be reachable.
define warn-unless-on-path
	case ":$$PATH:" in \
	  *":$(BINDIR):"*) ;; \
	  *) echo "warning: $(BINDIR) is not on your PATH; add it with" >&2; \
	     echo "  echo 'export PATH=\"$(BINDIR):\$$PATH\"' >>~/.bashrc" >&2 ;; \
	esac
endef

.PHONY: all deps build image image-nocache rebuild launcher

all: deps build

deps:
	$(MAKE) -C ../agents-base

build: image launcher

rebuild: image-nocache launcher

image:
	podman build -t $(IMAGE) .

image-nocache:
	podman build -t $(IMAGE) --no-cache .

# Refuse to clobber a real binary: several of these CLIs install themselves to
# ~/.local/bin under the same name.
launcher:
	@mkdir -p $(BINDIR)
	@if [ -e $(LAUNCHER) ] && ! grep -qF $(MARKER) $(LAUNCHER); then \
		echo "$(LAUNCHER) exists and was not generated here; refusing to overwrite" >&2; \
		exit 1; \
	fi
	@printf '%s\n' \
		'#!/bin/sh' \
		'# $(MARKER): generated by $(CURDIR)/Makefile, edits will be lost' \
		'$(strip exec $(DR) -v "$$HOME/.docker/$(IMAGE):/root" $(IMAGE) $(CMD) $(ARGS)) "$$@"' \
		> $(LAUNCHER)
	@chmod +x $(LAUNCHER)
	@echo "installed $(LAUNCHER)"
	@$(warn-unless-on-path)
