# Dracula with local tweaks, sourced by tmux.conf
# Background #22212c
source-file ~/.dotfiles/themes/dracula/tmux.conf

set -g mode-style 'bg=#f8f8f2,fg=#22212c'
set -g status-style 'bg=#22212c,fg=#6272a4'
set -g status-left '#{?client_prefix,#[bg=#f1fa8c],#[bg=#bd93f9]}#[fg=#22212c,bold] #S #[default] '

# vim: ft=tmux
