#!/usr/bin/env bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

BINARY="/usr/bin/7z"

FLAGS=(
  ${MIN_FLAGS[@]}
  --ro-bind /bin /bin
  --ro-bind /usr/bin /usr/bin
  --ro-bind /usr/lib /usr/lib
)
add_argdirs "$@" "$(pwd)"

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
