#!/usr/bin/env bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

BINARY="/usr/lib/p7zip/${BASH_SOURCE[0]##*/}"

FLAGS=(${MIN_FLAGS[@]})
add_argdirs "$@" "$(pwd)"

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
