#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${X11_FLAGS[@]}
  --ro-bind /etc /etc
  --ro-bind /usr/bin/eog /usr/bin/eog
  --ro-bind /var/cache/fontconfig /var/cache/fontconfig
  --ro-bind ~/.config/dconf ~/.config/dconf
  --ro-bind ~/.fonts ~/.fonts
  --unsetenv SESSION_MANAGER
)
add_argdirs "$@"

exec bwrap "${FLAGS[@]}" /usr/bin/eog "$@"
