#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${MIN_X11_FLAGS[@]}
  --share-net
  --bind /run/user/$UID/pulse /run/user/$UID/pulse
  --bind ~/.cache/mozilla ~/.cache/mozilla
  --bind ~/.mozilla ~/.mozilla
  --ro-bind /etc /etc
  --ro-bind ~/.config/pulse ~/.config/pulse
  --unsetenv DBUS_SESSION_BUS_ADDRESS
  --unsetenv SESSION_MANAGER
)
add_nvidia
add_argdirs ~/Downloads /share
add_argdirs_ro "$@"

mkdir -m 0700 -p ~/.cache/mozilla

BINARY=/usr/lib/firefox/firefox
if ! [[ -x "$BINARY" ]]; then
  BINARY=/usr/lib/firefox-esr/firefox-esr
fi

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
