#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

export GTK_CSD=1  # fix titlebar hiding in cinnamon

FLAGS=(
  ${X11_FLAGS[@]}
  --share-net
  --bind /run/user/$UID/pulse /run/user/$UID/pulse
  --bind ~/.cache/mozilla ~/.cache/mozilla
  --bind ~/.mozilla ~/.mozilla
  --ro-bind /etc /etc
  --ro-bind ~/.config ~/.config
  --unsetenv DBUS_SESSION_BUS_ADDRESS
  --unsetenv SESSION_MANAGER
)

if [[ -x /usr/bin/qpdfview ]]; then
  FLAGS+=(
    --bind /run/user/$UID/bus /run/user/$UID/bus
    --bind /run/user/$UID/dconf /run/user/$UID/dconf
    --bind ~/.config/qpdfview ~/.config/qpdfview
    --ro-bind /usr/bin/qpdfview /usr/bin/qpdfview
    --ro-bind /var/cache/fontconfig /var/cache/fontconfig
    --ro-bind ~/.fonts ~/.fonts
    --unsetenv SESSION_MANAGER
    --unsetenv QT_AUTO_SCREEN_SCALE_FACTOR
    --setenv QT_FONT_DPI 163
  )
fi

add_argdirs "$(realpath ~/Downloads)" /share
add_argdirs_ro "$@"

mkdir -m 0700 -p ~/.cache/mozilla

BINARY=/usr/lib/firefox/firefox
if ! [[ -x "$BINARY" ]]; then
  BINARY=/usr/lib/firefox-esr/firefox-esr
fi

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
