#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

BINARY=/usr/bin/geeqie

FLAGS=(
  ${X11_FLAGS[@]}
  --bind ~/.config/geeqie ~/.config/geeqie
  --ro-bind "$BINARY" "$BINARY"
  --ro-bind /etc /etc
  --ro-bind /var/cache/fontconfig /var/cache/fontconfig
  --ro-bind ~/.fonts ~/.fonts
  --unsetenv SESSION_MANAGER
)
add_argdirs_ro "$@"

mkdir -p -m 0700 ~/.config/geeqie

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
