#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

BINARY=$(realpath /usr/bin/libreoffice)
FLAGS=(
  ${MIN_X11_FLAGS[@]}
  --bind /run/user/$UID/bus /run/user/$UID/bus
  --bind /run/user/$UID/dconf /run/user/$UID/dconf
  --bind ~/.config/libreoffice ~/.config/libreoffice
  --ro-bind /bin /bin
  --ro-bind /etc /etc
  --ro-bind /usr/bin /usr/bin
  --unsetenv SESSION_MANAGER
)
add_argdirs "$@" /share ~/Downloads

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
