#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${X11_FLAGS[@]}
  --bind-try /run/user/$UID/pulse /run/user/$UID/pulse
  --ro-bind /etc /etc
  --ro-bind /usr/bin/mpv /usr/bin/mpv
  --ro-bind-try ~/.config/dconf ~/.config/dconf
  --ro-bind-try ~/.config/mpv ~/.config/mpv
  --ro-bind-try ~/.config/pulse ~/.config/pulse
  --unsetenv SESSION_MANAGER
)
add_nvidia

# i915
if ! [[ -c /dev/nvidiactl ]]; then
  FLAGS+=(
    --bind-try /dev/dri /dev/dri
    --ro-bind-try /sys /sys
  )
fi

for arg in "$@"; do
  if [[ "$arg" =~ ^https?://.* ]]; then
    FLAGS+=(--share-net)
  elif [[ -f "$arg" ]]; then
    FLAGS+=(--ro-bind "$arg" "$arg")
    if [[ -f "$arg.srt" ]]; then
      FLAGS+=(--ro-bind "$arg.srt" "$arg.srt")
    fi
  fi
done

bwrap "${FLAGS[@]}" /usr/bin/mpv -v --alang=eng,en --loop "$@" >/tmp/mpv.log 2>&1
exit $?
