#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${X11_FLAGS[@]}
  --ro-bind-try "${XDG_RUNTIME_DIR}/pulse" "${XDG_RUNTIME_DIR}/pulse"
  --ro-bind-try "${XDG_RUNTIME_DIR}/pipewire-0" "${XDG_RUNTIME_DIR}/pipewire-0"
  --ro-bind /usr/bin/mpv /usr/bin/mpv
  --ro-bind-try ~/.config/dconf ~/.config/dconf
  --ro-bind-try ~/.config/mpv ~/.config/mpv
  --ro-bind-try ~/.config/pulse ~/.config/pulse
  --unsetenv SESSION_MANAGER
)
add_gpu

for arg in "$@"; do
  if [[ "$arg" =~ ^https?://.* ]]; then
    FLAGS+=(--share-net)
  elif [[ -f "$arg" ]]; then
    FLAGS+=(--ro-bind "$(realpath "$arg")"  "$(realpath "$arg")")
    if [[ -f "$arg.srt" ]]; then
      FLAGS+=(--ro-bind "$(realpath "$arg.srt")"  "$(realpath "$arg.srt")")
    fi
  fi
done

bwrap "${FLAGS[@]}" /usr/bin/mpv -v --alang=eng,en --loop "$@" >/tmp/mpv.log 2>&1
exit $?
