#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

BINARY=/usr/bin/okular
FLAGS=(
  ${MIN_X11_FLAGS[@]}
  --bind /run/user/$UID/bus /run/user/$UID/bus
  --bind /run/user/$UID/dconf /run/user/$UID/dconf
  --bind ~/.config ~/.config
  --ro-bind "$BINARY" "$BINARY"
  --ro-bind /etc /etc
  --ro-bind /var/cache/fontconfig /var/cache/fontconfig
  --unsetenv SESSION_MANAGER
)
add_argdirs_ro "$@" /share ~/Downloads /s/study ~/.config/qt5ct ~/.icons ~/.fonts

exec bwrap "${FLAGS[@]}" "$BINARY" "$@"
