#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${MIN_X11_FLAGS[@]}
  --bind /run/user/$UID/bus /run/user/$UID/bus
  --bind /run/user/$UID/dconf /run/user/$UID/dconf
  --bind ~/.config/qpdfview ~/.config/qpdfview
  --ro-bind /etc /etc
  --ro-bind /usr/bin/qpdfview /usr/bin/qpdfview
  --ro-bind /var/cache/fontconfig /var/cache/fontconfig
  --ro-bind ~/.fonts ~/.fonts
  --unsetenv SESSION_MANAGER
  --unsetenv QT_AUTO_SCREEN_SCALE_FACTOR  # causes blurry rendering on 4K
  --setenv QT_FONT_DPI 163
)
add_argdirs_ro "$@"

mkdir -p -m 0700 ~/.config/qpdfview

exec bwrap "${FLAGS[@]}" /usr/bin/qpdfview "$@"
