#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${X11_FLAGS[@]}
  --ro-bind /home /home
  --bind /run/user/$UID/bus /run/user/$UID/bus
  --bind /run/user/$UID/dconf /run/user/$UID/dconf
  --ro-bind ~/.config ~/.config
  --bind ~/.config/qpdfview ~/.config/qpdfview
  --ro-bind /etc /etc
  --ro-bind /usr/bin/qpdfview /usr/bin/qpdfview
  --ro-bind /var/cache/fontconfig /var/cache/fontconfig
  --ro-bind ~/.fonts ~/.fonts
  --ro-bind / /
  --unsetenv SESSION_MANAGER
  --unsetenv QT_AUTO_SCREEN_SCALE_FACTOR  # causes blurry rendering on 4K
  --setenv QT_FONT_DPI 163
)
#add_argdirs_ro "$@" /s /nfs /s/home

mkdir -p -m 0700 ~/.config/qpdfview

set -x

exec bwrap "${FLAGS[@]}" /usr/bin/qpdfview "$@"
