#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

FLAGS=(
  ${MIN_X11_FLAGS[@]}
  --share-net
  --bind /run/user/$UID/bus /run/user/$UID/bus
  --bind /run/user/$UID/pulse /run/user/$UID/pulse
  --bind ~/.config/vlc ~/.config/vlc
  --bind ~/.local/share/vlc ~/.local/share/vlc
  --ro-bind /etc /etc
  --ro-bind /usr/bin/vlc /usr/bin/vlc
  --ro-bind ~/.config/dconf ~/.config/dconf
  --unsetenv SESSION_MANAGER
)
add_nvidia
add_argdirs_ro "$@" ~/Downloads /share

exec bwrap "${FLAGS[@]}" /usr/bin/vlc "$@"
