#!/bin/bash
SCRIPT=$(realpath -P -- "${BASH_SOURCE[0]}")
source "${SCRIPT%/*}/lib.sh"

mkdir -m 0700 -p ~/.config/vlc ~/.local/share/vlc

FLAGS=(
  ${X11_FLAGS[@]}
  --bind /run/user/$UID/pulse /run/user/$UID/pulse
  --bind ~/.config/vlc ~/.config/vlc
  --bind ~/.local/share/vlc ~/.local/share/vlc
  --ro-bind /etc /etc
  --ro-bind /usr/bin/vlc /usr/bin/vlc
  --ro-bind ~/.config/dconf ~/.config/dconf
  --unsetenv SESSION_MANAGER
)
if [[ -d /run/user/$UID/bus ]]; then
  FLAGS+=(--bind /run/user/$UID/bus /run/user/$UID/bus)
fi
add_nvidia
add_argdirs_ro "$@"

for arg in "$@"; do
  if [[ "$arg" =~ ^https?://.* ]]; then
    FLAGS+=(--share-net)
    break
  fi
done

exec bwrap "${FLAGS[@]}" /usr/bin/vlc "$@"
