#!/usr/bin/env bash

BRANCH="$1"
if [ -z "$BRANCH" ]; then
  BRANCH=empty
fi

set -e -x

cd .git

tree=`git mktree </dev/null`
commit=`echo Empty branch | git commit-tree $tree`
echo $commit >refs/heads/$BRANCH

echo Created branch "$BRANCH"
