#!/usr/bin/env python
# quick & dirty installation from tarballs
import os, re, sys

def sh(cmd):
    print cmd
    n = os.system(cmd)
    if n != 0:
        raise Exception('Command "%s" terminated with exit code %d' % (cmd, n)) 

def main(argv):
    if len(argv) < 2 or argv[1][0] == '-':
        print 'Usage: tarballinstall URL [/usr/local or its alternative]'
    url = argv[1]

    if len(argv) >= 3:
        local = argv[2]
    else:
        local = os.path.join(os.environ['HOME'], 'local')   # /home/user/local
    if not os.path.exists(local):
        print "Local directory ('%s') doesn't exist." % local
        return 1

    m = re.match(r'.*/(([^/]*)\.tar\.(gz|bz2))$', url)
    if not m:
        print "Couldn't parse the URL"
        return 1

    archive, basename, gz_bz2 = m.groups()

    if not os.path.exists(archive):
        sh("wget '%s'" % url)
    sh("tar %s '%s'" % (('-zxf' if (gz_bz2 == 'gz') else '-jxf'), archive))
    if not os.path.exists(basename):
        print 'Tarball wasn\'t extracted into "%s"' % basename
        return 1
    sh("cd '%s' && ./configure '--prefix=%s' && make && make install" % (basename, local))
    sh("rm -rf '%s'" % basename)

    print 'SUCCESS: Installed in %s' % local


main(sys.argv)
