FROM editors-base

# RUN git clone https://github.com/ivankra/dotfiles.git /root/.dotfiles && \
#     cd /root/.dotfiles/modules && make
# RUN /root/.dotfiles/setup.sh

# RUN nvim --headless "+Lazy! sync" "+qa"
# RUN nvim --headless "+MasonInstallAll" "+qa"
# RUN nvim --headless "+TSInstallSync all" "+qa"

# TODO: one time setup.sh --allow-root
